In [2]:
import pandas as pd
import numpy as np

In [20]:
df=pd.read_excel('auto generated video lists.xlsx')
type(df[['title','link']])
df[['title','link']]
# .iloc[[3,4,5,6],0]

,title,link
0,宋威龙 丝蕴 无硅水润,http://v.youku.com/v_show/id_XNDIyMzQwMTgzNg==...
1,宋威龙 瑞典 芭兰珂,http://v.youku.com/v_show/id_XNDIxNjU5NzIyNA==...
2,罗家文化2019视频集锦,http://v.youku.com/v_show/id_XNDE1ODk1NTA4MA==...
3,40,http://v.youku.com/v_show/id_XNDEwNjQwNjM0MA==...
4,33,http://v.youku.com/v_show/id_XNDEwMjg5MzA5Mg==...
5,55,http://v.youku.com/v_show/id_XNDEwMTYyNjg4NA==...
6,62,http://v.youku.com/v_show/id_XNDEwMTU5MjQzNg==...
7,施华蔻 王子异,http://v.youku.com/v_show/id_XNDEwMTU3NTYzNg==...
8,杜比 电影《复仇者联盟》活动现场,http://v.youku.com/v_show/id_XNDEwMTU2NjEyOA==...
9,巴黎卡诗,http://v.youku.com/v_show/id_XNDEwMTU3MTc5Mg==...
10,Dove_Draper,http://v.youku.com/v_show/id_XMzk2OTUzMzY5Ng==...
11,Bobbi Brown Crushed Lips,http://v.youku.com/v_show/id_XMzcxNTUwNzY3Mg==...
12,VICHY 薇姿水光焕白系列,http://v.youku.com/v_show/id_XMzY2MjA1MjU3Mg==...
13,罗家文化2018作品集锦,http://v.youku.com/v_show/id_XMzYxMjg4NzU4NA==...
14,非常认真的美食纪录片,http://v.youku.com/v_show/id_XMzUwODY5ODg5Ng==...
15,Syoss Mood Film,http://v.youku.com/v_show/id_XMzQ2MDczMTgwOA==...
16,Syoss StepByStep Video,http://v.youku.com/v_show/id_XMzQ2MDcxNzIzNg==...
17,Goodbaby,http://v.youku.com/v_show/id_XMzQ2MDY1Nzc4NA==...
18,Ashley Video Two,http://v.youku.com/v_show/id_XMzQ2MDY1NDcxMg==...
19,Ashley Video One,http://v.youku.com/v_show/id_XMzQ2MDY0NDA1Mg==...
20,《我是杀手》电影精彩片段3,http://v.youku.com/v_show/id_XMzQwMDI3OTI2NA==...
21,《我是杀手》电影精彩片段2,http://v.youku.com/v_show/id_XMzQwMDI3NzI1Ng==...
22,《我是杀手》电影精彩片段1,http://v.youku.com/v_show/id_XMzQwMDI2OTUyMA==...
23,电影《我是杀手》全网首发，城中顶尖杀手出没,http://v.youku.com/v_show/id_XMzM5NzYzMDE2OA==...
24,拿奖拿到手软的《我是杀手》终极版预告释出,http://v.youku.com/v_show/id_XMzM5NjI0MjQ5Mg==...
25,#电影#《我是杀手》新版预告片出炉,http://v.youku.com/v_show/id_XMzM5MDY5MDgwOA==...
26,《我是杀手》预告片1新鲜出炉,http://v.youku.com/v_show/id_XMzM4ODM1MjgzNg==...
27,LP Films showreel,http://v.youku.com/v_show/id_XMzMyODg1MzcyNA==...
28,The Killing Game 我是杀手,http://v.youku.com/v_show/id_XMzI3NDM2MDIyOA==...
29,罗家文化2017作品集锦,http://v.youku.com/v_show/id_XMzI0MDk1Mjk2MA==...
...,...,...
234,罗家文化日本之旅 2012 LPfilms Japan Trip,http://v.youku.com/v_show/id_XMzkxMTc5MDAw.html
235,Himalaya Time-lapse 喜马拉雅延时摄影,http://v.youku.com/v_show/id_XMzkwNjU5NzUy.html
236,Phenix菲尼克斯日本时尚短片,http://v.youku.com/v_show/id_XMzkwMTY1Mjgw.html
237,2008年100%设计上海国际家居装饰艺术展宣传片,http://v.youku.com/v_show/id_XMzg3ODE5MDIw.html
238,2010年100%设计上海展宣传片,http://v.youku.com/v_show/id_XMzg3ODI0NjE2.html
239,Phenix菲尼克斯广告片《定义卓越》,http://v.youku.com/v_show/id_XMzg2MjM3NDA0.html
240,Phenix菲尼克斯广告片《关键时刻的选择》,http://v.youku.com/v_show/id_XMzg2MjM3MDY4.html
241,Chelini家具宣传片,http://v.youku.com/v_show/id_XMzg2MjM2Mjk2.html
242,Phenix菲尼克斯广告片《注定成就你》,http://v.youku.com/v_show/id_XMzg2MjM0NDY0.html
243,上海扶轮社“生命的礼物”公益短片,http://v.youku.com/v_show/id_XMzgyMTYxMzY0.html
244,2010年上海国际家居装饰艺术展宣传片,http://v.youku.com/v_show/id_XMzU4Mzk2Mjk2.html
245,A-Zenith亚振家具宣传短片,http://v.youku.com/v_show/id_XMzU4Mzk0NTY4.html
246,上海古象大酒店宣传片-长版本,http://v.youku.com/v_show/id_XMzU3NTY5ODQ4.html
247,Parkway百汇医疗宣传片,http://v.youku.com/v_show/id_XMzU2MTI0MTA4.html
248,上海电气宣传片,http://v.youku.com/v_show/id_XMzU0NjM0MjY4.html
249,《茶秀》纪录片,http://v.youku.com/v_show/id_XMzIwODQ4NjE2.html
250,《茶秀》宣传片,http://v.youku.com/v_show/id_XMzIwODI2MjI0.html
251,定时拍摄短片《一个城市的窥探》,http://v.youku.com/v_show/id_XMzE5MjE3NjU2.html
252,《2010年上海世博会之上海企业联合馆纪录片》预告片,http://v.youku.com/v_show/id_XMzE5MjExNDY4.html
253,《2007世界夏季特殊奥林匹克运动会开幕式纪录片》预告片,http://v.youku.com/v_show/id_XMzE5MTcyMjcy.html
254,纪录片《阳关三叠》预告片,http://v.youku.com/v_show/id_XMzE4OTU5NzEy.html
255,2010年BASF巴斯夫企业形象宣传片,http://v.youku.com/v_show/id_XMzE4ODk3NTI0.html
256,罗家文化2011作品集锦,http://v.youku.com/v_show/id_XMzE4MjQwMTAw.html
257,泡菜先生，教你做菜,http://v.youku.com/v_show/id_XMjY5MzM4NDA0.html
258,泡菜先生，教你做菜——第2集,http://v.youku.com/v_show/id_XMjY5MzMzMDY0.html
259,泡菜先生，教你做菜——第1集,http://v.youku.com/v_show/id_XMjY5MzI4ODc2.html
260,2009年上海国际田径黄金大奖赛电视广告片-冲刺到底,http://v.youku.com/v_show/id_XMjQ5NDc4MTI0.html
261,2008年上海国际田径黄金大奖赛电视广告片-里弄英雄,http://v.youku.com/v_show/id_XMjQ5NDAwNzA0.html
262,Moganshan House 23 莫干山经典别墅,http://v.youku.com/v_show/id_XNzk3NTkwODg=.html
263,上海企业联合馆创意团队介绍,http://v.youku.com/v_show/id_XNzI2NzIzMDg=.html

In [11]:
#df = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'))
df = pd.DataFrame(np.array(np.arange(12).reshape(4,3)), columns=list('bde'))

In [3]:
df.head()

   b   d   e
0  0   1   2
1  3   4   5
2  6   7   8
3  9  10  11

In [4]:
df[df['b'] > 6]

   b   d   e
3  9  10  11

In [5]:
df[df['b'] > 6]['d']

3    10
Name: d, dtype: int32

In [6]:
df['d'].describe()

count     4.000000
mean      5.500000
std       3.872983
min       1.000000
25%       3.250000
50%       5.500000
75%       7.750000
max      10.000000
Name: d, dtype: float64

In [7]:
df['d'].unique

<bound method Series.unique of 0     1
1     4
2     7
3    10
Name: d, dtype: int32>

In [8]:
len(df)

4

In [9]:
df.groupby('e')['b'].mean()

e
2     0
5     3
8     6
11    9
Name: b, dtype: int32

In [10]:
df.groupby('e')['b'].mean().sort_values(ascending=False)

e
11    9
8     6
5     3
2     0
Name: b, dtype: int32

In [11]:
df['b*e'] = df['b']*df['e']

In [12]:
df.head()

   b   d   e  b*e
0  0   1   2    0
1  3   4   5   15
2  6   7   8   48
3  9  10  11   99